name: Deploy Bicep-NewAVD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az login --service-principal \
            -u ${{ secrets.AZURE_CLIENT_ID }} \
            -p ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
          echo "Validating deployment..."
          az deployment group what-if \
            --resource-group Azure-GK-RG3 \
            --template-file ./workload/bicep/brownfield/newSessionHosts/deploy.bicep \
            --parameters ./workload/bicep/brownfield/newSessionHosts/parameters/new-session-hosts.parameters.all.bicepparam

          echo "Deploying Bicep template..."
          az deployment group create \
            --resource-group Azure-GK-RG3 \
            --template-file ./workload/bicep/brownfield/newSessionHosts/deploy.bicep \
            --parameters ./workload/bicep/brownfield/newSessionHosts/parameters/new-session-hosts.parameters.all.bicepparam
